<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" ignored="0" total="7" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="29042" started-at="2018-04-08T17:52:35Z" finished-at="2018-04-08T17:53:04Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="29042" started-at="2018-04-08T17:52:35Z" finished-at="2018-04-08T17:53:04Z">
      <class name="softtest.DashboardTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:softtest.DashboardTest@e45f292]" name="setup" is-config="true" duration-ms="3378" started-at="2018-04-08T17:52:35Z" finished-at="2018-04-08T17:52:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="setup()[pri:0, instance:softtest.LoginTest@6fd02e5]" name="setup" is-config="true" duration-ms="2330" started-at="2018-04-08T17:52:39Z" finished-at="2018-04-08T17:52:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="setup()[pri:0, instance:softtest.LogoutTest@5bcab519]" name="setup" is-config="true" duration-ms="2313" started-at="2018-04-08T17:52:41Z" finished-at="2018-04-08T17:52:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="displayCurrencyFxRateTest()[pri:0, instance:softtest.DashboardTest@e45f292]" name="displayCurrencyFxRateTest" duration-ms="6653" started-at="2018-04-08T17:52:47Z" finished-at="2018-04-08T17:52:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- displayCurrencyFxRateTest -->
        <test-method status="PASS" signature="displayCurrencyTest()[pri:0, instance:softtest.DashboardTest@e45f292]" name="displayCurrencyTest" duration-ms="6144" started-at="2018-04-08T17:52:54Z" finished-at="2018-04-08T17:53:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- displayCurrencyTest -->
        <test-method status="FAIL" signature="notDisplayedCurrencyTest()[pri:0, instance:softtest.DashboardTest@e45f292]" name="notDisplayedCurrencyTest" duration-ms="2273" started-at="2018-04-08T17:53:00Z" finished-at="2018-04-08T17:53:02Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[expected:<0> but was:<32>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: expected:<0> but was:<32>
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.failNotEquals(Assert.java:282)
at junit.framework.Assert.assertEquals(Assert.java:64)
at junit.framework.Assert.assertEquals(Assert.java:201)
at junit.framework.Assert.assertEquals(Assert.java:207)
at softtest.DashboardTest.notDisplayedCurrencyTest(DashboardTest.java:76)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- notDisplayedCurrencyTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:softtest.DashboardTest@e45f292]" name="tearDown" is-config="true" duration-ms="654" started-at="2018-04-08T17:53:02Z" finished-at="2018-04-08T17:53:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:softtest.LoginTest@6fd02e5]" name="tearDown" is-config="true" duration-ms="648" started-at="2018-04-08T17:53:03Z" finished-at="2018-04-08T17:53:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:softtest.LogoutTest@5bcab519]" name="tearDown" is-config="true" duration-ms="712" started-at="2018-04-08T17:53:04Z" finished-at="2018-04-08T17:53:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- softtest.DashboardTest -->
      <class name="softtest.LogoutTest">
        <test-method status="FAIL" signature="SignoutTest()[pri:0, instance:softtest.LogoutTest@5bcab519]" name="SignoutTest" duration-ms="1393" started-at="2018-04-08T17:52:46Z" finished-at="2018-04-08T17:52:47Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[Testfail]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: Testfail
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertFalse(Assert.java:34)
at softtest.LogoutTest.SignoutTest(LogoutTest.java:52)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SignoutTest -->
      </class> <!-- softtest.LogoutTest -->
      <class name="softtest.LoginTest">
        <test-method status="FAIL" signature="EmptyUIDPasswordTest()[pri:0, instance:softtest.LoginTest@6fd02e5]" name="EmptyUIDPasswordTest" duration-ms="1406" started-at="2018-04-08T17:52:43Z" finished-at="2018-04-08T17:52:45Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[expected:<Dashboard> but was:<[[ChromeDriver: chrome on XP (0c421901e76300866c5714b41cdc7750)] -> xpath: //h1[@class='h2'][contains(text(),'Dashboard')]]]]><![CDATA[>expected:<Dashboard> but was:<[[ChromeDriver: chrome on XP (0c421901e76300866c5714b41cdc7750)] -> xpath: //h1[@class='h2'][contains(text(),'Dashboard')]]><![CDATA[]]]]><![CDATA[>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: expected:<Dashboard> but was:<[[ChromeDriver: chrome on XP (0c421901e76300866c5714b41cdc7750)] -> xpath: //h1[@class='h2'][contains(text(),'Dashboard')]]]]><![CDATA[>
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.failNotEquals(Assert.java:282)
at junit.framework.Assert.assertEquals(Assert.java:64)
at junit.framework.Assert.assertEquals(Assert.java:71)
at softtest.LoginTest.EmptyUIDPasswordTest(LoginTest.java:97)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EmptyUIDPasswordTest -->
        <test-method status="FAIL" signature="NegativeUIDPasswordTest()[pri:0, instance:softtest.LoginTest@6fd02e5]" name="NegativeUIDPasswordTest" duration-ms="491" started-at="2018-04-08T17:52:45Z" finished-at="2018-04-08T17:52:45Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[expected:<Dashboard> but was:<[[ChromeDriver: chrome on XP (0c421901e76300866c5714b41cdc7750)] -> xpath: //h1[@class='h2'][contains(text(),'Dashboard')]]]]><![CDATA[>expected:<Dashboard> but was:<[[ChromeDriver: chrome on XP (0c421901e76300866c5714b41cdc7750)] -> xpath: //h1[@class='h2'][contains(text(),'Dashboard')]]><![CDATA[]]]]><![CDATA[>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: expected:<Dashboard> but was:<[[ChromeDriver: chrome on XP (0c421901e76300866c5714b41cdc7750)] -> xpath: //h1[@class='h2'][contains(text(),'Dashboard')]]]]><![CDATA[>
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.failNotEquals(Assert.java:282)
at junit.framework.Assert.assertEquals(Assert.java:64)
at junit.framework.Assert.assertEquals(Assert.java:71)
at softtest.LoginTest.NegativeUIDPasswordTest(LoginTest.java:75)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NegativeUIDPasswordTest -->
        <test-method status="PASS" signature="PositiveTest()[pri:0, instance:softtest.LoginTest@6fd02e5]" name="PositiveTest" duration-ms="596" started-at="2018-04-08T17:52:45Z" finished-at="2018-04-08T17:52:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PositiveTest -->
      </class> <!-- softtest.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
